language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
node_js:
  - "node"
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install -g bower
before_deploy:
  - bower install jquery --config.directory=components
  - git clone https://github.com/hunsalz/web-socket components/web-socket
  - echo "<META http-equiv="refresh" content=\"0;URL=components/web-socket/\">" >index.html
deploy:
  provider: pages
  github-token: $GH_PAGES_TOKEN
  skip-cleanup: true
  keep-history: true
  verbose: true
  on:
    branch: master